from wsba_hockey.wsba_main import (
    # Scrape functions
    nhl_scrape_game,
    nhl_scrape_schedule,
    nhl_scrape_season,
    nhl_scrape_seasons_info,
    nhl_scrape_standings,
    nhl_scrape_game_roster,
    nhl_scrape_roster,
    nhl_scrape_draft_rankings,
    nhl_scrape_prospects,
    nhl_scrape_player_info,
    nhl_scrape_team_info,
    nhl_scrape_game_info,
    nhl_scrape_edge,
    nhl_scrape_seasons,
    nhl_scrape_event_data,

    # Calculation functions
    nhl_calculate_stats,
    nhl_agg_stats,
    nhl_apply_xG,

    # Plotting functions
    nhl_plot_events,

    # Repository functions
    repo_load_rosters,
    repo_load_schedule,
    repo_load_teaminfo,
    
    # Utility functions
    utility_get_schema,
    utility_get_unique
)

from wsba_hockey.tools.http import make_pooled_session

__version__ = "1.7.0"

from wsba_hockey.tools.globals import (
    A3Z_STRENGTH_FIXES,
    A3Z_TEAM_FIXES,
    AGG_POST_METRICS,
    BIO_STAT_COL,
    BOOLEAN,
    COL_MAP,
    CONTEXT_FIXES,
    CONTINUOUS,
    CONVERT_SEASONS,
    CONVERT_TEAM_ABBR,
    CV_PATH,
    DATASET_COL,
    DEFAULT_AGG,
    DEFAULT_ROSTER,
    DIR,
    DRAFT_CAT,
    EDGE_CAT,
    ENTRY_TYPES,
    EVENTS,
    EVENT_MARKERS,
    FENWICK_EVENTS,
    FRONT_COL,
    GAME_SCORE,
    GS_SCORE_FEATURES,
    IMG_PATH,
    INFO_PATH,
    KNOWN_PROBS,
    LANE_FIXES,
    LEGEND_ELEMENTS,
    METRIC_EVENTS,
    METRIC_LOOKUP,
    METRIC_PATH,
    NON_FINAL_STATES,
    NON_TOTALS,
    OPS,
    PACKAGE_DIR,
    PBP_COLS,
    PER_SIXTY,
    POS_BASE_PROB,
    RESULT_FIXES,
    RESULT_NAMES,
    SCHEDULE_PATH,
    SEASON_NAMES,
    SHOT_TYPES,
    SPECIAL_KEYS,
    STANDINGS_COLS,
    STATS_SORT,
    STRENGTHS,
    STRENGTH_GROUPS,
    STRENGTH_MAP,
    STRENGTH_MATCH,
    TARGET,
    TEAM_IDS,
    TEAM_NAME_TO_ABBR,
    TEAMS,
    TEST_PATH,
    XG_MODEL_DIR,
    XG_MODEL,
    convert_to_seconds,
    get_contents,
    get_soup,
    get_team,
    get_teams,
)
